Add cache build config to structure config yaml
griptape-ai/managed-structure-template pull request #12
Opened 2024-07-30 20:52 UTC by zachgiordano

* Add cache build config to structure config yaml
* Update README

2024-07-30 21:27 UTC, SavagePencil approved these changes

2024-07-31 14:13 UTC, dylanholmes approved these changes
Had some related suggestions in https://github.com/griptape-ai/griptape-sample-structures/pull/5#pullrequestreview-2210276108

2024-07-31 18:32 UTC, SavagePencil requested changes

2024-07-31 18:32 UTC, SavagePencil commented on README.md
> +When `cache_build_dependencies` is enabled, Griptape Cloud will cache the base runtime dependencies for the Structure for reuse on subsequent Deployments. That cache will be invalidated when any of t
Can we move the sentence `This speeds up the Deployment process, especially for Structures with many dependencies.` to be right after `When `cache_build_dependencies` is enabled, Griptape Cloud will cache the base runtime dependencies for the Structure for reuse on subsequent Deployments.` so we can get the value up front sooner?

2024-07-31 18:32 UTC, SavagePencil commented on structure_config.yaml
> +      - requirements.txt
can we just mirror the comments from the README here?

2024-07-31 18:46 UTC, SavagePencil approved these changes

2024-07-31 18:58 UTC, merged